sequenceDiagram
    autonumber
    actor Formateur
    participant Ctrl as TacheController
    participant TS as TacheService (PkgCreationTache)
    participant RP_S as RealisationProjetService (PkgRealisationProjets)
    participant RTS as RealisationTacheService (PkgRealisationTache)

    Note over Ctrl, RTS: USE CASE : Ajouter une Tâche (Propagation aux Réalisations)

    Formateur->>Ctrl: POST /taches (data)
    Ctrl->>TS: create(data)
    activate TS
    TS->>TS: DB Insert Tache
    
    Note right of TS: Hook afterCreateRules
    TS->>RP_S: getActiveRealisationsForProject(projet_id)
    RP_S-->>TS: Collection<RealisationProjet>
    
    loop Pour chaque RealisationProjet
        TS->>RTS: createRealisation(tache_id, realisation_projet_id)
        Note right of TS: SRP: TS délègue la création<br/>de la réalisation à RTS.
    end
    TS-->>Ctrl: Tache Created & Propagated
    deactivate TS
